import json
import pandas as pd
import matplotlib.pyplot as plt

# Load the JSON array into a Pandas DataFrame
data = json.loads('''[
 {
   "SKU": "00-27650",
   "Spex Generated Categories": "SPEX_AUTOGENERATED_1009_Other Accessories",
   "Product Status": "Disabled",
   "Store Category ID": "95",
   "Category": "Other Accessories",
   "Spec Field (Rich Text)": "\n<ul>\n\t<li>Beginer&nbsp;guitar instructional book</li>\n\t<li>Includes DVD&nbsp;</li>\n</ul>\n"
 },
 {
   "SKU": "00-907760",
   "Spex Generated Categories": "SPEX_Books/Journals",
   "Product Status": "Enabled",
   "Store Category ID": "303",
   "Category": "Other Accessories",
   "Spec Field (Rich Text)": "<h1>Alfred Music Publishing SongXpress: Early Rock &amp; Roll, Vol. 1 DVD</h1><ul><li>Songs On DVD:</li><ul><li>Blue Suede Shoes (Elvis Presley)</li><li>Oh, Pretty Woman (Roy Orbison)</li><li>That'll Be the Day (Buddy Holly)</li><li>Wake Up Little Susie (The Everly Brothers)</li></ul></ul><p>&nbsp;</p>"
 }]''')

df = pd.DataFrame(data)

# Create a stacked bar chart showing the distribution of products by category and store category
counts = df.groupby(['Category', 'Store Category ID']).size().unstack(fill_value=0)
ax = counts.plot(kind='bar', stacked=True)

# Set chart labels and titles
ax.set_xlabel('Category')
ax.set_ylabel('Count')
ax.set_title('Product Distribution by Category and Store Category')

# Show the chart
plt.show()
